// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: logger/logger.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "logger";

export interface LogRequest {
  /** info, error, warn, debug */
  level: string;
  message: string;
  /** service name */
  service: string;
  /** controller/class name */
  context: string;
  /** correlation ID */
  traceId: string;
  timestamp: string;
  /** additional fields */
  metadata: { [key: string]: string };
}

export interface LogRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface LogBatchRequest {
  logs: LogRequest[];
}

export interface LogResponse {
  success: boolean;
  message: string;
}

export const LOGGER_PACKAGE_NAME = "logger";

export interface LoggerServiceClient {
  log(request: LogRequest): Observable<LogResponse>;

  logBatch(request: LogBatchRequest): Observable<LogResponse>;
}

export interface LoggerServiceController {
  log(request: LogRequest): Promise<LogResponse> | Observable<LogResponse> | LogResponse;

  logBatch(request: LogBatchRequest): Promise<LogResponse> | Observable<LogResponse> | LogResponse;
}

export function LoggerServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["log", "logBatch"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("LoggerService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("LoggerService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const LOGGER_SERVICE_NAME = "LoggerService";
