// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: user/user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface Empty {
}

export interface FindOneRequest {
  id: string;
}

export interface CreateUserRequest {
  name: string;
  email: string;
}

export interface UserResponse {
  id: string;
  name: string;
  email: string;
}

export interface UsersResponse {
  users: UserResponse[];
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  findOne(request: FindOneRequest): Observable<UserResponse>;

  create(request: CreateUserRequest): Observable<UserResponse>;

  findAll(request: Empty): Observable<UsersResponse>;
}

export interface UserServiceController {
  findOne(request: FindOneRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  create(request: CreateUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  findAll(request: Empty): Promise<UsersResponse> | Observable<UsersResponse> | UsersResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["findOne", "create", "findAll"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
